[package]
name = "market_matcher_rs"
version = "0.1.0"
authors = ["White-Oak <lpzhelud@gmail.com>"]
edition = "2018"

[dependencies]
failure = "*"
chrono = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"

